version: '3.8'

networks:
  network:
    driver: bridge

volumes:
  postgres_data:

services:
  api:
    build:
      context: .
      dockerfile: EMDR42.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5010
    ports:
      - '5010:5010'
    depends_on:
      - db
    networks:
      - network
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    emvironment:
      - DB_HOST
      - DB_PORT
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_EMAIL
      - SMTP_PASSWORD
      - JWT_KEY
      - JWT_ISSUER

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2208
      POSTGRES_DB: EMDR
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network